<?php

namespace KsUtils\StrFilter;

require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/StrFilter.php";
require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/StrFilter/DtFromRus.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
 */
class DtFromRusTest extends \PHPUnit_Framework_TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DtFromRus;
    }

    /**
     * @covers KsUtils\StrFilter\DtFromRus::filter()
     */
    public function testFilter()
    {
        $this->assertEquals("2013-12-31", $this->object->filter("31.12.2013"));
        $this->assertEquals("", $this->object->filter("abc"));
        $this->assertEquals("", $this->object->filter(" 31.12.2013  "));
        $this->assertEquals("", $this->object->filter("31122013"));
        $this->assertEquals("", $this->object->filter("12/31/2013"));
    }
}