<?php

namespace KsUtils\StrFilter;

require_once realpath(dirname(__FILE__) . "/../../../src") . "/StrFilter.php";
require_once realpath(dirname(__FILE__) . "/../../../src") . "/StrFilter/StripNonDigit.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
 */
class StripNonDigitTest extends \PHPUnit_Framework_TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StripNonDigit;
    }

    /**
     * @covers KsUtils\StrFilter\StripNonDigit::filter()
     */
    public function testFilter()
    {
        $this->assertEquals("", $this->object->filter(""));
        $this->assertEquals("", $this->object->filter("abc"));
        $this->assertEquals("12345", $this->object->filter("12345"));
        $this->assertEquals("1234567", $this->object->filter("123-45-67"));
        $this->assertEquals("123", $this->object->filter("ab1cd2de3gh"));
        $this->assertEquals("123", $this->object->filter("1+2=3"));
    }
}