<?php

namespace KsUtils\StrFilter;

require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/StrFilter.php";
require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/StrFilter/Trim.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
 */
class TrimTest extends \PHPUnit_Framework_TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Trim;
    }

    /**
     * @covers KsUtils\StrFilter\Trim::filter()
     */
    public function testFilter()
    {
        $this->assertNull($this->object->filter(null));
        $this->assertEquals("", $this->object->filter(""));
        $this->assertEquals("abc", $this->object->filter("abc"));
        $this->assertEquals("abc", $this->object->filter("  abc  "));
        $this->assertEquals("abc def ghi", $this->object->filter("  abc def ghi "));
        $this->assertEquals(array("aaa", "dfd", "bvbn"), $this->object->filter(array("  aaa  ", " dfd", "  bvbn     ")));
        
    }
}