<?php

    namespace KsUtils;

    /**
     * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
     */
    class DtTest extends \PHPUnit_Framework_TestCase
    {

        /**
         * @var Dt
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
            $this->object = new Dt;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {

        }

        /**
         * @covers KsUtils\Dt::rus2int
         * @todo   Implement testRus2int().
         */
        public function testRus2int()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Dt::int2rus
         * @todo   Implement testInt2rus().
         */
        public function testInt2rus()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

    }

