<?php

    namespace KsUtils;

    /**
     * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
     */
    class PagerTest extends \PHPUnit_Framework_TestCase
    {

        /**
         * @var Pager
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
            $this->object = new Pager;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {

        }

        /**
         * @covers KsUtils\Pager::getOnpage
         * @todo   Implement testGetOnpage().
         */
        public function testGetOnpage()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::setOnpage
         * @todo   Implement testSetOnpage().
         */
        public function testSetOnpage()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::getItemsTotal
         * @todo   Implement testGetItemsTotal().
         */
        public function testGetItemsTotal()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::getItems
         * @todo   Implement testGetItems().
         */
        public function testGetItems()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::getPagesTotal
         * @todo   Implement testGetPagesTotal().
         */
        public function testGetPagesTotal()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::getCurPage
         * @todo   Implement testGetCurPage().
         */
        public function testGetCurPage()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::setItemsTotal
         * @todo   Implement testSetItemsTotal().
         */
        public function testSetItemsTotal()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::setItems
         * @todo   Implement testSetItems().
         */
        public function testSetItems()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::setPagesTotal
         * @todo   Implement testSetPagesTotal().
         */
        public function testSetPagesTotal()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

        /**
         * @covers KsUtils\Pager::setCurPage
         * @todo   Implement testSetCurPage().
         */
        public function testSetCurPage()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                'This test has not been implemented yet.'
            );
        }

    }

