<?php

namespace KsUtils\Validator;

require_once realpath(dirname(__FILE__) . "/../../../src") . "/Validator.php";
require_once realpath(dirname(__FILE__) . "/../../../src") . "/Validator/NotEmpty.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
 */
class NotEmptyTest extends \PHPUnit_Framework_TestCase
{
    /**
     *
     * @var NotEmpty
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NotEmpty;
    }

    /**
     * @covers KsUtils\Validator\NotEmpty::check()
     */
    public function testCheck()
    {
        $this->assertTrue($this->object->check("abc"));
        $this->assertTrue($this->object->check("a"));
        $this->assertTrue($this->object->check(0));
        $this->assertTrue($this->object->check(123));
        $this->assertFalse($this->object->check(null));
        $this->assertFalse($this->object->check(""));
        $this->assertFalse($this->object->check(" "));

        $this->assertEquals(
            "Must not be empty: ",
            $this->object->getError("")
        );

        $this->assertEquals(
            "Must not be empty: ",
            $this->object->getError(null)
        );
    }

}