<?php

namespace KsUtils\Validator;

require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/Validator.php";
require_once realpath(dirname(__FILE__) . "/../../../../src/KsUtils") . "/Validator/Date.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 15:14:58.
 */
class DateTest extends \PHPUnit_Framework_TestCase
{
    /**
     *
     * @var Date
     */
    protected $object;
    /**
     *
     * @var Date
     */
    protected $objectRus;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Date;
        $this->objectRus = new Date("d.m.Y");
        $this->objectRus->setErrorTpl("У даты [%s] неверный формат");
    }

    /**
     * @covers KsUtils\Validator\Date::__construct()
     * @covers KsUtils\Validator\Date::hasError()
     * @covers KsUtils\Validator::check()
     * @covers KsUtils\Validator::getError()
     * @covers KsUtils\Validator::setErrorTpl()
     */
    public function testCheck()
    {
        $this->assertTrue($this->object->check("2013-12-31"));
        $this->assertFalse($this->object->check("31.12.2013"));
        $this->assertFalse($this->object->check("12abc12"));
        $this->assertEquals("Wrong date: 12abc12", $this->object->getError("abc"));
        
        $this->assertTrue($this->objectRus->check("31.12.2013"));
        $this->assertFalse($this->objectRus->check("2013-12-31"));
        $this->assertFalse($this->objectRus->check("12/31/2013"));
        $this->assertEquals("У даты [12/31/2013] неверный формат", $this->objectRus->getError("abc123"));
    }
}